name: Code Checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # Check out the repository first.
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm install prettier-plugin-svelte
      - uses: actionsx/prettier@v3
        with:
          # prettier CLI arguments.
          args: --plugin=prettier-plugin-svelte  --check .
