name: Code Checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm install --save-dev prettier-plugin-svelte eslint
      - name: Prettier
        run: npm run prettier-check
      - name: Eslint
        run: npm run eslint-check
      - name: TSC
        run: npm run typescript-check
